<a href="https://colab.research.google.com/github/Malki9/3601763_BD2/blob/main/3601763_BD2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Libraries

In [71]:
# Import the required libaries
import pandas as pd
import pandas as np
import json
import re

### Load the Dataset

In [73]:
# Create variables and load the .csv datasets
# Added on_bad_lines='skip' to handle formatting errors in the reviews file
products = pd.read_csv('/content/products.csv')
reviews = pd.read_csv('/content/reviews.csv')
users = pd.read_csv('/content/users.csv')

In [72]:
# Read the file and try to parse it line-by-line manually to avoid 'Trailing data' errors
products_list = []
with open('/content/jcpenney_products.json', 'r') as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                products_list.append(json.loads(line))
            except json.JSONDecodeError:
                # If a single line fails, it might be the start/end of a standard array
                continue

if not products_list:
    # If line-by-line failed, try reading the whole file as one array
    with open('/content/jcpenney_products.json', 'r') as f:
        jcpenney_products = pd.DataFrame(json.load(f))
else:
    jcpenney_products = pd.DataFrame(products_list)

# Load reviewers (usually works fine with lines=True)
jcpenney_reviewers = pd.read_json('/content/jcpenney_reviewers.json', lines=True)

print('Data loaded successfully')

Data loaded successfully

In [74]:
jcpenney_reviewers.head(4)

,Username,DOB,State,Reviewed
0,bkpn1412,31.07.1983,Oregon,[cea76118f6a9110a893de2b7654319c0]
1,gqjs4414,27.07.1998,Massachusetts,[fa04fe6c0dd5189f54fe600838da43d3]
2,eehe1434,08.08.1950,Idaho,[]
3,hkxj1334,03.08.1969,Florida,"[f129b1803f447c2b1ce43508fb822810, 3b0c9bc0be6..."

In [63]:
jcpenney_products.head(4)

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,product_image_urls,brand,total_number_reviews,Reviews,Bought With
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'fsdv4141', 'Review': 'You never hav...","[898e42fe937a33e8ce5e900ca7a4d924, 8c02c262567..."
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,3.000,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'tpcu2211', 'Review': 'You never hav...","[bc9ab3406dcaa84a123b9da862e6367d, 18eb69e8fc2..."
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'pcfg3234', 'Review': 'You never hav...","[3ce70f519a9cfdd85cdbdecd358e5347, b0295c96d2b..."
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.500,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'ngrq4411', 'Review': 'You never hav...","[efcd811edccbeb5e67eaa8ef0d991f7c, 7b2cc00171e..."

In [64]:
jcpenney_products.head(4)

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,product_image_urls,brand,total_number_reviews,Reviews,Bought With
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'fsdv4141', 'Review': 'You never hav...","[898e42fe937a33e8ce5e900ca7a4d924, 8c02c262567..."
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,3.000,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'tpcu2211', 'Review': 'You never hav...","[bc9ab3406dcaa84a123b9da862e6367d, 18eb69e8fc2..."
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'pcfg3234', 'Review': 'You never hav...","[3ce70f519a9cfdd85cdbdecd358e5347, b0295c96d2b..."
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.500,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'ngrq4411', 'Review': 'You never hav...","[efcd811edccbeb5e67eaa8ef0d991f7c, 7b2cc00171e..."

In [65]:
# Checking whether the indexes are correct and no repeating indexes
jcpenney_reviewers.head(4)

,Username,DOB,State,Reviewed
0,bkpn1412,31.07.1983,Oregon,[cea76118f6a9110a893de2b7654319c0]
1,gqjs4414,27.07.1998,Massachusetts,[fa04fe6c0dd5189f54fe600838da43d3]
2,eehe1434,08.08.1950,Idaho,[]
3,hkxj1334,03.08.1969,Florida,"[f129b1803f447c2b1ce43508fb822810, 3b0c9bc0be6..."

In [66]:
reviews.head(4)

,Uniq_id,Username,Score,Review
0,b6c0b6bea69c722939585baeac73c13d,fsdv4141,2,You never have to worry about the fit...Alfred...
1,b6c0b6bea69c722939585baeac73c13d,krpz1113,1,Good quality fabric. Perfect fit. Washed very ...
2,b6c0b6bea69c722939585baeac73c13d,mbmg3241,2,I do not normally wear pants or capris that ha...
3,b6c0b6bea69c722939585baeac73c13d,zeqg1222,0,I love these capris! They fit true to size and...

In [67]:
products.head(4)

,Uniq_id,SKU,Name,Description,Price,Av_Score
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.000
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.500

In [68]:
users.head(4)

   Username         DOB          State
0  bkpn1412  31.07.1983         Oregon
1  gqjs4414  27.07.1998  Massachusetts
2  eehe1434  08.08.1950          Idaho
3  hkxj1334  03.08.1969        Florida

### Data Exploration

In [75]:
# check the dataframes basic information like the datatype
users.info()
jcpenney_products.info()
jcpenney_reviewers.info()
products.info()
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  5000 non-null   object
 1   DOB       5000 non-null   object
 2   State     5000 non-null   object
dtypes: object(3)
memory usage: 117.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7982 entries, 0 to 7981
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uniq_id                 7982 non-null   object
 1   sku                     7982 non-null   object
 2   name_title              7982 non-null   object
 3   description             7982 non-null   object
 4   list_price              7982 non-null   object
 5   sale_price              7982 non-null   object
 6   category                7982 non-null   object
 7   category_tree           7982 non-null   object
 8   average_product_rating  7982 non-null   float64
 9   product_url             7982 non-null   object
 10  product_image_urls      7982 non-null   object
 11  brand                   7982 non-null   object
 12  total_number_reviews    7982 non-null   int64
 13  Reviews                 7982 non-null   object
 14  Bought With             7982 non-null   object
dtypes: float64(1), int64(1), object(13)
memory usage: 935.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  5000 non-null   object
 1   DOB       5000 non-null   object
 2   State     5000 non-null   object
 3   Reviewed  5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7982 entries, 0 to 7981
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Uniq_id      7982 non-null   object
 1   SKU          7915 non-null   object
 2   Name         7982 non-null   object
 3   Description  7439 non-null   object
 4   Price        5816 non-null   float64
 5   Av_Score     7982 non-null   float64
dtypes: float64(2), object(4)
memory usage: 374.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39063 entries, 0 to 39062
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Uniq_id   39063 non-null  object
 1   Username  39063 non-null  object
 2   Score     39063 non-null  int64
 3   Review    39063 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.2+ MB

In [82]:
# Summary statistics
jcpenney_products.describe()

       average_product_rating  total_number_reviews
count             7982.000000           7982.000000
mean                 2.988683              4.893886
std                  0.911673              3.314284
min                  1.000000              1.000000
25%                  2.500000              2.000000
50%                  3.000000              4.000000
75%                  3.500000              8.000000
max                  5.000000             23.000000

In [100]:
# Check for null values in each dataframe as a count
# Display in a tabular format
# Function to create the dataframe consist of column and sum
def null_summary(dataset):
    return pd.DataFrame({
        "column": dataset.columns,
        "sum": dataset.isnull().sum().values
    })

# Create summaries of each dataframe
users_null = null_summary(users)
jc_reviews_null = null_summary(jcpenney_reviewers)
jc_products_null = null_summary(jcpenney_products)
products_null = null_summary(products)
reviews_null = null_summary(reviews)

# Put all in dictionary
tables = {
    "users": users_null,
    "jcpenney_reviews": jc_reviews_null,
    "jc_products": jc_products_null,
    "products": products_null,
    "reviews": reviews_null
}

# Find maximum number of rows
max_rows = max(len(dataset) for dataset in tables.values())

# Pad smaller tables
for name, dataset in tables.items():
    if len(dataset) < max_rows:
        padding = pd.DataFrame({
            "column": [""] * (max_rows - len(dataset)),
            "sum": [""] * (max_rows - len(dataset))
        })
        tables[name] = pd.concat([dataset, padding], ignore_index=True)

# Create final aligned table
final_table = pd.concat(tables, axis=1)

final_table

       users     jcpenney_reviews                 jc_products       \
      column sum           column sum                  column  sum
0   Username   0         Username   0                 uniq_id    0
1        DOB   0              DOB   0                     sku    0
2      State   0            State   0              name_title    0
3                        Reviewed   0             description  543
4                                                  list_price    0
5                                                  sale_price    0
6                                                    category    0
7                                               category_tree    0
8                                      average_product_rating    0
9                                                 product_url    0
10                                         product_image_urls    0
11                                                      brand    0
12                                       total_number_reviews    0
13                                                    Reviews    0
14                                                Bought With    0

       products         reviews
         column   sum    column sum
0       Uniq_id     0   Uniq_id   0
1           SKU    67  Username   0
2          Name     0     Score   0
3   Description   543    Review   0
4         Price  2166
5      Av_Score     0
6
7
8
9
10
11
12
13
14

In [98]:
products['SKU'] = products['SKU'].str.strip()
products['SKU'] = products['SKU'].replace(' ', pd.NA)

In [99]:
products['SKU'].isnull().sum()

np.int64(67)

In [92]:
# get the summary statistics of all the vaiables including categorical variables in all the dataset
jcpenney_products.describe(include='all')

# Count the categories of each sku
jcpenney_products['sku'].value_counts()

sku
                67
pp5006210554    18
pp5004560042    16
pp5006990582    15
pp5002781170    14
                ..
1afd48a          1
pp5003950738     1
pp5007010088     1
pp5006080460     1
pp5006480847     1
Name: count, Length: 6044, dtype: int64

In [93]:
''' Sometimes the some attributes has nan which are considered to be string values and hence they are not couted as null. Need to eliminate those as well.
This happens for attributes which are catergorical'''
# Iterate through each dataset and identify in each column that nan values are there which are strings
datasets = [users, jcpenney_reviewers, jcpenney_products, products, reviews]
for dataset in datasets:
    for column in dataset.columns:
      if dataset[column].dtype == 'object'and dataset[column].str.contains('nan').any():
          # Replace the values with NaN
          dataset[column] = dataset[column].replace('', pd.NA)
          dataset[column] = dataset[column].replace(' ', pd.NA)
          dataset[column] = dataset[column].replace('nan', pd.NA)

In [ ]:
# The users act as the base dataset which is linked with the jcpenney_reviewers and reviews dataset
# Check the Username column in the users, jcpenny_reviews and reviews dataset follows the same standard
# Import the libary re
import re
# Define the pattern where the first 04 char are simple letters from a-z and the last for as int from 0-9
pattern = r'^[a-z]{4}[0-9]{4}$'
# Get the unique values in each of the dataset of username columns as a Dictionary
users_username = { 'users' : set(users['Username']), # convert the username column to set, eliminates the duplicates
                   'reviews': set(reviews['Username']),
                   'jcpenney_reviewers' : set(jcpenney_reviewers['Username'])
                   }

# Iterate through each value in the users_username
for key, value in users_username.items():
  invalid_found = False
  for username in value:
    if not re.fullmatch(pattern, username):
      print(f" Invalid username in {key}: {username}")
      invalid_found = True
  if not invalid_found: print(f" All usernames in {key} are in the particular standard")

 All usernames in users are in the particular standard
 All usernames in reviews are in the particular standard
 All usernames in jcpenney_reviewers are in the particular standard

In [37]:
# Iterate through each column in the jcpenney product and identify whether the product details (such as SKU) are same as the products using Unique_id
for column in products.columns:
  # Check the iterated column is uniq_id
  if column == 'Uniq_id':
    unmatch = False
    # Iterate through each value in the products
    for uniq_id in jcpenney_products['uniq_id']:
      if uniq_id not in products['Uniq_id'].values:
        print(f"Unique_id {uniq_id} not found in products")
        unmatch = True

    if not unmatch:
      print(f"All the Unique_id found in products are there in the Jcpenny_product.json file")

  elif column == 'sku':
    unmatch = False
    # Iterate through each value in the
    for product_name in products['SKU']:
      if product_name not in jcpenney_products['sku'].values:
        print(f"SKU {product_name} not found in jcpenney_products")
        unmatch = True

    if not unmatch:
      print(f"All the SKU found in jcpenney_products are there in the producsts csv")

All the Unique_id found in products are there in the Jcpenny_product.json file

In [36]:
for uniq_id in jcpenney_products['uniq_id']:

    # Check if uniq_id exists in products
    if uniq_id in products['Uniq_id'].values:

        # Get SKU from both datasets
        sku_products = products.loc[products['Uniq_id'] == uniq_id, 'SKU'].values[0]
        sku_jc = jcpenney_products.loc[jcpenney_products['uniq_id'] == uniq_id, 'sku'].values[0]

        # Compare SKU
        if sku_products != sku_jc:
            print(f"Mismatch for Unique_id {uniq_id}:")
            print(f"   products SKU = {sku_products}")
            print(f"   jcpenney SKU = {sku_jc}")

    else:
        print(f"Unique_id {uniq_id} not found in products")

Mismatch for Unique_id ada678a4523077b3bc62f9f418972507:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 97d2d2ce9f22fb3218f724324097d988:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 6d3177f25b852be96c858f2d85f37f4c:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 08daf20a62b797053019a926687abb53:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id fc213145168faa94bae198f173d27796:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 43aa8a676fef64c914f46aaf34b8a0e2:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 7efc9da483e1d094b93ccdf9e9998241:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 0563348ce32c1a86bd897690ccb672d4:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id e08e41d720d8ef75e71ad1f09962bc2b:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id e10b8cd3fc58b5cee61127f106ca1a61:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 621dd67ec08d2388203b6f338038a328:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id d1d38dfea72cb77d2be3e6efbf7a515c:
   products SKU = 1.44E+04
   jcpenney SKU = 14350e0
Mismatch for Unique_id 9bf32f5c5dddad97cd7f0bb7e4e3b7cc:
   products SKU = 1.81E+12
   jcpenney SKU = 18110e8
Mismatch for Unique_id 4e08453c9624741b7a5a45d732321d23:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id dfab765fc1694b1a73001dc2d8a9acda:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id bd849e80b7c2cdab52333b28d821b0f9:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id f83b1fed1ede51ebfb3e915cc2a3962d:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id a1085ec663fa0c01a2b4919e064230c7:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 33320bb9ce46b174706e8bc88a5fafe1:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 62ec1712f9f230fcbbf1a2281b13fe8d:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 329208459808c24e53ef8a53f987fbfa:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 327d0404fbac7aef476f13132f8f7d38:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id b8e18fa03cf44389214b3772cb846f05:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 90a0b9a7f4da7e93cc6a8f5960f7e4a3:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 37c970e6e2ea953566fdb27362e0c5a1:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 58a83088e85703f0d1040f320464fac9:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 46690964e4105821e0604822ed0a44bb:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id a9c9ba2180ec5a5d750f4d0a559e2866:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 3ccc2a2fd818e501fd138288bdb8bf48:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 5d82fdb364af4724a9a3bb29f798db83:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 6d601908e1712ec65940356d607eb4ab:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 3a15a9899294363d44e09a58ba400f82:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 31babfaed4ea91bc810afe3e2d04d19d:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id fc6a4836c97bdd34364bbeaafad93858:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 8460df17307111e9d2b56a2df11f5177:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 2d3863b32dcec2742be67e2aa50ece93:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 549ab12eea3fde46efdc6c280b3fda73:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id f1520f9fa8737c46de02cf83206591c3:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id a270d2a55377cdb1b06cdb4d676a1b9d:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 5b79bc60c166f2c09169d949788d6cc8:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id a9861148829d25894572e39e00e84af3:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 1edc6b476b180bf9c40e9390a874ba6a:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id f98a0de072d044405bb87f17238462f4:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id e3b57c0bea5052c53719c354ea1e4f27:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id e1c2691f324aedc88ae05964e2c745d7:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 9af2d553c748b737d54b17a80c19a2aa:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 480eb155267b422aac8828e33efbb8d5:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 121fd2f8102c2fc4dc1fb0634dfd6fea:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 6c9bf9ec67986c692b85bdac3ce792d4:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id d0c3bce0b5299cd03bf4236aef9f57b0:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 79c3aaff478e99f983db63d4e89af938:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 75df75a7f5d103716cc2d79113a06bf9:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 7a27c6bd09bbc9c1360e1304a3ae764c:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 490f1c363beaaf875385010fb12e55df:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 6885e09a0b5a646a59cfdf6b5e8d21ad:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id a7c9f786497e08942c89e7c063259586:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 16ccbb55e35d59d7e3bdeb571013ef4c:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id ac01494eb5a94842ab06a56070be2717:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id d08691d7b28e69226d82304862611f6b:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 75e03f12dc56ea6d8b09be180c924080:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 3c693d9b340c8f62b3aa3ccdf0bda959:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id f4ae254c25f1a3191b23cee6ac9a396d:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id ad869fddd25ce5633089b10994aca073:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id c3042190506249df31a0959589f70f3d:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 7c84f3b2ded021a89585d9fb2feb499b:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id a318ae67b92bb8bb7dc11d5c6ce6217a:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 82ab722bb511148cb9925d6bf63a2006:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id aab2f41dc9e92b44945ccad3774c10ad:
   products SKU = nan
   jcpenney SKU =
Mismatch for Unique_id 9bc9196be34a52dae59dac1c68c305a9:
   products SKU = nan
   jcpenney SKU =

In [ ]:
# Check Username is consitent over users dataframe and jcpenny_reviewers
# Define a dictionary variable and assign the columns as set
users_username = {
    'users' : set(users['Username']), # convert the username column to set, eliminates the duplicates
    'jcpenney_reviewers' : set(jcpenney_reviewers['Username'])
}

# Intersect to get the common values
username_common = set.intersection(*users_username.values())
print(f'The number of users common among the two dataset : {len(username_common)}')

The number of users common among the two dataset : 4999

All the users in user.csv exists in jcpenny_reviews

In [ ]:
# check the duplicated Username in the users

In [ ]:
# checking whether all the users in jcpenny_reviewers are there in users.csv
jcpenney_reviewers.Username.isin(users.Username).value_counts()

In [ ]:
# checking whether all the unique_id are matches with the products and reviews
products.Uniq_id.isin(jcpenney_products.uniq_id).value_counts()

In [ ]:
# Extracting the Uniq_id code which does not match
products[~jcpenney_products.uniq_id.isin(products.Uniq_id)]

In [ ]:
# combine the dataset user.csv and reviews with username
users = pd.merge(users, reviews, on='Username')

In [ ]:
users

In [ ]:
# Identifying the types of the Data in the dataframes .reviews
reviews.info()

In [ ]:
reviews

In [ ]:
# Converting the Score column/ data type to numeric
reviews['Score'] = pd.to_numeric(reviews['Score'], errors='coerce')

In [ ]:
reviews.describe()

In [ ]:
# Checking whether the average score in products given to unique_id is the same as the average of the scores in reviews


reviews.groupby('Uniq_id')['Score'].mean()

# Checking the mean of the scores in reviews with the Av_Score

In [50]:
# Extracting a record inJcpenny_products where the Uniq_id is 000bde718ab945188a364aab4d8bcfaa
record = products.loc[products['SKU'] ==  'nan']

In [51]:
record

Empty DataFrame
Columns: [Uniq_id, SKU, Name, Description, Price, Av_Score]
Index: []

In [ ]:
# Now that jcpenney_products is restored, we can perform the merge
comparison = jcpenney_products.merge(products, left_on='uniq_id', right_on='Uniq_id', how='inner')

In [ ]:
comparison

In [ ]:
match_count = comparison['score_match'].value_counts()

In [ ]:
match_count

In [ ]:
# extracting the  Unique_id, average_product_rating, Av_Score columns of the unmathed scores
unmatched_scores = comparison[comparison['score_match'] == False][['uniq_id', 'average_product_rating', 'Av_Score', 'Uniq_id']]

In [ ]:
comparison.info()

In [ ]:
unmatched_scores

In [ ]:
type(jcpenney_products)

In [ ]:
jcpenney_products.astype(str).duplicated().sum()

In [ ]:
# Dropping the duplicate records correctly
# We remove inplace=True when assigning back to the variable to ensure it returns the new DataFrame
jcpenney_products = jcpenney_products.astype(str).drop_duplicates()