<a href="https://colab.research.google.com/github/Malki9/3601763_BD2/blob/main/3601763_BD2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# University of Stirling

# ITNPBD2 Representing and Manipulating Data

# Assignment Spring 2026

# A Consultancy Job for JC Penney

This notebook forms the assignment instructions and submission document of the assignment for ITNPBD2. Read the instructions carefully and enter code into the cells as indicated.

You will need these five files, which were in the Zip file you downloaded from the course webpage:

- jcpenney_reviewers.json
- jcpenney_products.json
- products.csv
- reviews.csv
- users.csv

The data in these files describes products that have been sold by the American retail giant, JC Penney, and reviews by customers who bought them. Note that the product data is real, but the customer data is synthetic.

Your job is to process the data, as requested in the instructions in the markdown cells in this notebook.

# Completing the Assignment

Rename this file to be xxxxxx_BD2 where xxxxxx is your student number, then type your code and narrative description into the boxes provided. Add as many code and markdown cells as you need. The cells should contain:

- **Text narrative describing what you did with the data**
- **The code that performs the task you have described**
- **Comments that explain your code**

The final structure (in PDF) of your report must:
- **Start from the main insights observed (max 5 pages)**
- **Include as an appendix the source code used for producing those insights (max 15 pages)**
- **Include an AI cover sheet (provided on Canvas), which must contain a link to a versioned notebook file in OneDrive or another platform for version checks.**

# Marking Scheme
The assessment will be marked against the university Common Marking Scheme (CMS)

Here is a summary of what you need to achieve to gain a grade in the major grade bands:

|Grade|Requirement|
|:---|:---|
| Fail | You will fail if your code does not run or does not achieve even the basics of the task. You may also fail if you submit code without either comments or a text explanation of what the code does.|
| Pass | To pass, you must submit sufficient working code to show that you have mastered the basics of the task, even if not everything works completely. You must include some justifications for your choice of methods, but without mentioning alternatives. |
| Merit | For a merit, your code must be mostly correct, with only small problems or parts missing, and your comments must be useful rather than simply re-stating the code in English. Most choices for methods and structures should be explained and alternatives mentioned. |
| Distinction | For a distinction, your code must be working, correct, and well commented and shows an appreciation of style, efficiency and reliability. All choices for methods and structures are concisely justified and alternatives are given well thought considerations. For a distinction, your work should be good enough to present to executives at the company.|

The full details of the CMS can be found here

https://www.stir.ac.uk/about/professional-services/student-academic-and-corporate-services/academic-registry/academic-policy-and-practice/quality-handbook/assessment-policy-and-procedure/appendix-2-postgraduate-common-marking-scheme/

Note that this means there are not certain numbers of marks allocated to each stage of the assignment. Your grade will reflect how well your solutions and comments demonstrate that you have achieved the learning outcomes of the task.

## Submission
When you are ready to submit, **print** your notebook as PDF (go to File -> Print Preview) in the Jupyter menu. Make sure you have run all the cells and that their output is displayed. Any lines of code or comments that are not visible in the pdf should be broken across several lines. You can then submit the file online.

Late penalties will apply at a rate of three marks per day, up to a maximum of 7 days. After 7 days you will be given a mark of 0. Extensions will be considered under acceptable circumstances outside your control.

## Academic Integrity

This is an individual assignment, and so all submitted work must be fully your own work.

The University of Stirling is committed to protecting the quality and standards of its awards. Consequently, the University seeks to promote and nurture academic integrity, support staff academic integrity, and support students to understand and develop good academic skills that facilitate academic integrity.

In addition, the University deals decisively with all forms of Academic Misconduct.

Where a student does not act with academic integrity, their work or behaviour may demonstrate Poor Academic Practice or it may represent Academic Misconduct.

### Poor Academic Practice

Poor Academic Practice is defined as: "The submission of any type of assessment with a lack of referencing or inadequate referencing which does not effectively acknowledge the origin of words, ideas, images, tables, diagrams, maps, code, sound and any other sources used in the assessment."

### Academic Misconduct

Academic Misconduct is defined as: "any act or attempted act that does not demonstrate academic integrity and that may result in creating an unfair academic advantage for you or another person, or an academic disadvantage for any other member or member of the academic community."

Plagiarism is presenting somebody else’s work as your own **and includes the use of artificial intelligence tools beyond AIAS Level 2 or the use of Large Language Models.**. Plagiarism is a form of academic misconduct and is taken very seriously by the University. Students found to have plagiarised work can have marks deducted and, in serious cases, even be expelled from the University. Do not submit any work that is not entirely your own. Do not collaborate with or get help from anybody else with this assignment.

The University of Stirling's full policy on Academic Integrity can be found at:

https://www.stir.ac.uk/about/professional-services/student-academic-and-corporate-services/academic-registry/academic-policy-and-practice/quality-handbook/academic-integrity-policy-and-academic-misconduct-procedure/

## The Assignment
Your task with this assignment is to use the data provided to demonstrate your Python data manipulation skills.

There are three `.csv` files and two `.json` files so you can process different types of data. The files also contain unstructured data in the form of natural language in English and links to images that you can access from the JC Penney website (use the field called `product_image_urls`).

Start with easy tasks to show you can read in a file, create some variables and data structures, and manipulate their contents. Then move onto something more interesting.

Look at the data that we provided with this assessment and think of something interesting to do with it using whatever libraries you like. Describe what you decide to do with the data and why it might be interesting or useful to the company to do it.

You can add additional data if you need to - either download it or access it using `requests`. Produce working code to implement your ideas in as many cells as you need below. There is no single right answer, the aim is to simply show you are competent in using python for data analysis. Exactly how you do that is up to you.

For a distinction class grade, this must show originality, creative thinking, and insights beyond what you've been taught directly on the module.

## Structure
You may structure the appendix of the project how you wish, but here is a suggested guideline to help you organise your work, based on the CRISP-DM data science methodology:

 1. **Business understanding** - What business context is the data coming from? What insights would be valuable in that context, and what data would be required for that purporse?
 2. **Data understanding and preparation** - Explore the data and show you understand its structure and relations, with the aid of appropriate visualisation techniques. Assess the data quality, which insights you would be able to answer from it, and what preparation the data would require. Add new data from another source if required to bring new insights to the data you already have.
 3. **Data modeling (optional)** - Would modeling be required for the insights you have considered? Use appropriate techniques, if so.
 4. **Evaluation and deployment** - How do the insights you obtained help the company, and how can should they be adopted in their business? If modeling techniques have been adopted, are their use scientifically sound and how should they be mantained?

# Remember to make sure you are working completely on your own.
# Don't work in a group or with a friend

### Import Libraries

In [1]:
# Put your code and comments in cells below here
# Add as many cells as you need

In [2]:
# Import the required libaries
import pandas as pd
import pandas as np

### Load the Dataset

In [3]:
# Create variables and load the .csv datasets
# Added on_bad_lines='skip' to handle formatting errors in the reviews file
products = pd.read_csv('/content/products.csv')
reviews = pd.read_csv('/content/reviews.csv', on_bad_lines='skip')
users = pd.read_csv('/content/users.csv')

In [4]:
import json
import pandas as pd

# More robust loading for jcpenney_products.json
# We read the file and try to parse it line-by-line manually to avoid 'Trailing data' errors
products_list = []
with open('/content/jcpenney_products.json', 'r') as f:
    for line in f:
        line = line.strip()
        if line:
            try:
                products_list.append(json.loads(line))
            except json.JSONDecodeError:
                # If a single line fails, it might be the start/end of a standard array
                continue

if not products_list:
    # If line-by-line failed, try reading the whole file as one array
    with open('/content/jcpenney_products.json', 'r') as f:
        jcpenney_products = pd.DataFrame(json.load(f))
else:
    jcpenney_products = pd.DataFrame(products_list)

# Load reviewers (usually works fine with lines=True)
jcpenney_reviewers = pd.read_json('/content/jcpenney_reviewers.json', lines=True)

print('Data loaded successfully')
display(jcpenney_products.head())

Data loaded successfully

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,product_image_urls,brand,total_number_reviews,Reviews,Bought With
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'fsdv4141', 'Review': 'You never hav...","[898e42fe937a33e8ce5e900ca7a4d924, 8c02c262567..."
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,3.000,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'tpcu2211', 'Review': 'You never hav...","[bc9ab3406dcaa84a123b9da862e6367d, 18eb69e8fc2..."
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'pcfg3234', 'Review': 'You never hav...","[3ce70f519a9cfdd85cdbdecd358e5347, b0295c96d2b..."
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.500,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'ngrq4411', 'Review': 'You never hav...","[efcd811edccbeb5e67eaa8ef0d991f7c, 7b2cc00171e..."
4,d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.125,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'nbmi2334', 'Review': 'You never hav...","[0ca5ad2a218f59eb83eec1e248a0782d, 9869fc8da14..."

In [5]:
jcpenney_reviewers

,Username,DOB,State,Reviewed
0,bkpn1412,31.07.1983,Oregon,[cea76118f6a9110a893de2b7654319c0]
1,gqjs4414,27.07.1998,Massachusetts,[fa04fe6c0dd5189f54fe600838da43d3]
2,eehe1434,08.08.1950,Idaho,[]
3,hkxj1334,03.08.1969,Florida,"[f129b1803f447c2b1ce43508fb822810, 3b0c9bc0be6..."
4,jjbd1412,26.07.2001,Georgia,[]
...,...,...,...,...
4995,mfnn1212,27.07.1997,Delaware,[d6cd506246bd17afa611b6a06236713c]
4996,ejnb3414,01.08.1976,Minnesota,[97de1506cd0bcbe50f2797cd0588eb81]
4997,pdzw1433,28.07.1994,Ohio,"[799d62906019d910fa744987da184ae7, b8f5deb7b02..."
4998,npha1342,07.08.1953,Montana,[6250b1d691cd3842f05b87736f2fadbf]
4999,yuoc2324,02.08.1975,South Dakota,[]

In [6]:
jcpenney_products

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,product_image_urls,brand,total_number_reviews,Reviews,Bought With
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'fsdv4141', 'Review': 'You never hav...","[898e42fe937a33e8ce5e900ca7a4d924, 8c02c262567..."
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,3.000,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'tpcu2211', 'Review': 'You never hav...","[bc9ab3406dcaa84a123b9da862e6367d, 18eb69e8fc2..."
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'pcfg3234', 'Review': 'You never hav...","[3ce70f519a9cfdd85cdbdecd358e5347, b0295c96d2b..."
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.500,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'ngrq4411', 'Review': 'You never hav...","[efcd811edccbeb5e67eaa8ef0d991f7c, 7b2cc00171e..."
4,d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.125,http://www.jcpenney.com/alfred-dunner-essentia...,http://s7d9.scene7.com/is/image/JCPenney/DP122...,Alfred Dunner,8,"[{'User': 'nbmi2334', 'Review': 'You never hav...","[0ca5ad2a218f59eb83eec1e248a0782d, 9869fc8da14..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14731,16e3ca6b6a2d3f5da9a81df6cfe7e27a,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,130.67,view all brands,jcpenney|for-the-home|view all brands,3.875,http://www.jcpenney.com/hoover-windtunnel-upri...,http://s7d9.scene7.com/is/image/JCPenney/DP032...,Hoover,8,"[{'User': 'cced4433', 'Review': '1) the hose i...","[30611c465e893326b8b676ccc5e9e42b, 799d6290601..."
14732,209bec04d9f194616358a77d7b41b314,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,130.67,sale,jcpenney|for-the-home|sale,3.250,http://www.jcpenney.com/hoover-windtunnel-upri...,http://s7d9.scene7.com/is/image/JCPenney/DP032...,Hoover,8,"[{'User': 'rtbj4421', 'Review': '1) the hose i...","[ac4dcfeca034e705ac2be1a79bbe3acf, c2300c3e551..."
14733,7a8a7cba7b69b4c46ceac1d9666d84f0,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,130.67,vacuums & floorcare,jcpenney|for-the-home|vacuums & floorcare,2.500,http://www.jcpenney.com/hoover-windtunnel-upri...,http://s7d9.scene7.com/is/image/JCPenney/DP032...,Hoover,8,"[{'User': 'qven4314', 'Review': '1) the hose i...","[fc831da1b1d09b0bd7d6893e9615232f, 9f5f2c625d4..."
14734,9887bb20c12be3c09d094e97ac8d22be,pp5005921226,Hope Chest Embroidered Quilt & Accessories,,,35.63142,comforters & bedding sets,jcpenney|bed-bath|comforters & bedding sets,3.500,http://www.jcpenney.com/hope-chest-embroidered...,http://s7d9.scene7.com/is/image/JCPenney/DP072...,Asstd National Brand,8,"[{'User': 'sguz3424', 'Review': 'This product ...","[9968d41d84274b22610278d352f0753a, 7ff057a74f7..."
14735,2cc49292b44cc12fe22206440d3e7472,pp5005921226,Hope Chest Embroidered Quilt & Accessories,,,35.63142,quilts,jcpenney|bed-bath|quilts,3.000,http://www.jcpenney.com/hope-chest-embroidered...,http://s7d9.scene7.com/is/image/JCPenney/DP072...,Asstd National Brand,8,"[{'User': 'kcqh1322', 'Review': 'This product ...","[0516719d2624c741610b1815b3d92db9, 81fd62e56b8..."

In [7]:
reviews

,Uniq_id,Username,Score,Review
0,b6c0b6bea69c722939585baeac73c13d,fsdv4141,2,You never have to worry about the fit...Alfred...
1,b6c0b6bea69c722939585baeac73c13d,krpz1113,1,Good quality fabric. Perfect fit. Washed very ...
2,b6c0b6bea69c722939585baeac73c13d,mbmg3241,2,I do not normally wear pants or capris that ha...
3,b6c0b6bea69c722939585baeac73c13d,zeqg1222,0,I love these capris! They fit true to size and...
4,b6c0b6bea69c722939585baeac73c13d,nvfn3212,3,This product is very comfortable and the fabri...
...,...,...,...,...
61551,2cc49292b44cc12fe22206440d3e7472,whxp1433,2,This bedspread is as practical as it is beauti...
61552,2cc49292b44cc12fe22206440d3e7472,kfqi4333,1,I purchased this same wedding ring quilt 16 ye...
61553,2cc49292b44cc12fe22206440d3e7472,bynj4221,0,This was a gift for my daughter and she loves ...
61554,2cc49292b44cc12fe22206440d3e7472,eawq2222,1,I purchased these pillow shams as well as the ...
61555,2cc49292b44cc12fe22206440d3e7472,mcxs2141,1,Needed a new quilt for my newly remodeled bedr...

In [8]:
products

,Uniq_id,SKU,Name,Description,Price,Av_Score
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.000
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.500
4,d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.125
...,...,...,...,...,...,...
7977,16e3ca6b6a2d3f5da9a81df6cfe7e27a,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,3.875
7978,209bec04d9f194616358a77d7b41b314,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,3.250
7979,7a8a7cba7b69b4c46ceac1d9666d84f0,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,2.500
7980,9887bb20c12be3c09d094e97ac8d22be,pp5005921226,Hope Chest Embroidered Quilt & Accessories,NaN,NaN,3.500
7981,2cc49292b44cc12fe22206440d3e7472,pp5005921226,Hope Chest Embroidered Quilt & Accessories,NaN,NaN,3.000

In [9]:
users

      Username         DOB          State
0     bkpn1412  31.07.1983         Oregon
1     gqjs4414  27.07.1998  Massachusetts
2     eehe1434  08.08.1950          Idaho
3     hkxj1334  03.08.1969        Florida
4     jjbd1412  26.07.2001        Georgia
...        ...         ...            ...
4995  mfnn1212  27.07.1997       Delaware
4996  ejnb3414  01.08.1976      Minnesota
4997  pdzw1433  28.07.1994           Ohio
4998  npha1342  07.08.1953        Montana
4999  yuoc2324  02.08.1975   South Dakota

[5000 rows x 3 columns]

### Data Exploration

In [10]:
# checking the datframes basic information like the datatype
users.info()
jcpenney_products.info()
jcpenney_reviewers.info()
products.info()
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  5000 non-null   object
 1   DOB       5000 non-null   object
 2   State     5000 non-null   object
dtypes: object(3)
memory usage: 117.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14736 entries, 0 to 14735
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uniq_id                 14736 non-null  object
 1   sku                     14736 non-null  object
 2   name_title              14736 non-null  object
 3   description             14735 non-null  object
 4   list_price              14734 non-null  object
 5   sale_price              14734 non-null  object
 6   category                14734 non-null  object
 7   category_tree           14734 non-null  object
 8   average_product_rating  14734 non-null  float64
 9   product_url             14734 non-null  object
 10  product_image_urls      14734 non-null  object
 11  brand                   14736 non-null  object
 12  total_number_reviews    14736 non-null  int64
 13  Reviews                 14736 non-null  object
 14  Bought With             14736 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 1.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Username  5000 non-null   object
 1   DOB       5000 non-null   object
 2   State     5000 non-null   object
 3   Reviewed  5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7982 entries, 0 to 7981
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Uniq_id      7982 non-null   object
 1   SKU          7915 non-null   object
 2   Name         7982 non-null   object
 3   Description  7439 non-null   object
 4   Price        5816 non-null   float64
 5   Av_Score     7982 non-null   float64
dtypes: float64(2), object(4)
memory usage: 374.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61556 entries, 0 to 61555
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Uniq_id   61556 non-null  object
 1   Username  61556 non-null  object
 2   Score     61553 non-null  object
 3   Review    61551 non-null  object
dtypes: object(4)
memory usage: 1.9+ MB

In [11]:
# checking whether all the users in jcpenny_reviewers are there in users.csv
jcpenney_reviewers.Username.isin(users.Username).value_counts()

Username
True    5000
Name: count, dtype: int64

In [12]:
# checking whether all the unique_id are matches with the products and reviews
products.Uniq_id.isin(jcpenney_products.uniq_id).value_counts()

Uniq_id
True     7976
False       6
Name: count, dtype: int64

In [13]:
# Extracting the Uniq_id code which does not match
products[~jcpenney_products.uniq_id.isin(products.Uniq_id)]

/tmp/ipython-input-1229626615.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  products[~jcpenney_products.uniq_id.isin(products.Uniq_id)]

Empty DataFrame
Columns: [Uniq_id, SKU, Name, Description, Price, Av_Score]
Index: []

In [14]:
# combine the dataset user.csv and reviews with username
users = pd.merge(users, reviews, on='Username')

In [15]:
users

,Username,DOB,State,Uniq_id,Score,Review
0,bkpn1412,31.07.1983,Oregon,2565bf02ec05a59cd1fd78955dda108d,0,Love this heated mattress pad! Ordered the que...
1,bkpn1412,31.07.1983,Oregon,cea76118f6a9110a893de2b7654319c0,0,I like the jacket accept it is thin not and th...
2,bkpn1412,31.07.1983,Oregon,bc177e6724df06c676fd526e6d32461d,2,"Soft, comfortable, and it fits nice. Whats not..."
3,bkpn1412,31.07.1983,Oregon,a0d0f5f772021d6320048dc7b61fb551,5,I bought the quick dri bath rug in the size 21...
4,bkpn1412,31.07.1983,Oregon,1e7ddcdf95f8a77b31510ddb644eaefb,2,I love these sketchers. I love the color mix i...
...,...,...,...,...,...,...
61574,yuoc2324,02.08.1975,South Dakota,a0a2728d337eb267165a390131a4da7a,0,"love these capris. Light weight, so comfortabl..."
61575,yuoc2324,02.08.1975,South Dakota,bb7ab34ab5f534a8561d39c1e9da7a62,1,Good fit and fabric. I m 57 tall and weigh 170...
61576,yuoc2324,02.08.1975,South Dakota,711d50a83117df8311ce3e2a90a85995,1,"I was so pleased with the softness, color, and..."
61577,yuoc2324,02.08.1975,South Dakota,44725052ce6761bf358322761c8cfb2d,1,Very nice weight and fit. Very happy with this...
61578,yuoc2324,02.08.1975,South Dakota,722115c731f1f8ab57c9f1c9d5577007,1,I bought this for my boyfriend and he loved it...

In [14]:
# Identifying the types of the Data in the dataframes .reviews
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61556 entries, 0 to 61555
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Uniq_id   61556 non-null  object
 1   Username  61556 non-null  object
 2   Score     61553 non-null  object
 3   Review    61551 non-null  object
dtypes: object(4)
memory usage: 1.9+ MB

In [15]:
reviews

,Uniq_id,Username,Score,Review
0,b6c0b6bea69c722939585baeac73c13d,fsdv4141,2,You never have to worry about the fit...Alfred...
1,b6c0b6bea69c722939585baeac73c13d,krpz1113,1,Good quality fabric. Perfect fit. Washed very ...
2,b6c0b6bea69c722939585baeac73c13d,mbmg3241,2,I do not normally wear pants or capris that ha...
3,b6c0b6bea69c722939585baeac73c13d,zeqg1222,0,I love these capris! They fit true to size and...
4,b6c0b6bea69c722939585baeac73c13d,nvfn3212,3,This product is very comfortable and the fabri...
...,...,...,...,...
61551,2cc49292b44cc12fe22206440d3e7472,whxp1433,2,This bedspread is as practical as it is beauti...
61552,2cc49292b44cc12fe22206440d3e7472,kfqi4333,1,I purchased this same wedding ring quilt 16 ye...
61553,2cc49292b44cc12fe22206440d3e7472,bynj4221,0,This was a gift for my daughter and she loves ...
61554,2cc49292b44cc12fe22206440d3e7472,eawq2222,1,I purchased these pillow shams as well as the ...
61555,2cc49292b44cc12fe22206440d3e7472,mcxs2141,1,Needed a new quilt for my newly remodeled bedr...

In [16]:
# Converting the Score column/ data type to numeric
reviews['Score'] = pd.to_numeric(reviews['Score'], errors='coerce')

In [17]:
reviews.describe()

              Score
count  61551.000000
mean       1.492665
std        1.404047
min        0.000000
25%        0.000000
50%        1.000000
75%        2.000000
max        5.000000

In [20]:
# Checking whether the average score in products given to unique_id is the same as the average of the scores in reviews


reviews.groupby('Uniq_id')['Score'].mean()

# Checking the mean of the scores in reviews with the Av_Score

Uniq_id
000bde718ab945188a364aab4d8bcfaa    1.875000
000d4454259343ead2729c56f01b63dd    0.000000
000db764b3c4f52badbe24ce4c79bb31    1.888889
001221f2f59bebae47ddbd7ae2472410    0.666667
0017caf0fa3f54f4e9cf99f9238d3a16    1.000000
                                      ...
ffcb9d8bcae951a1a9bfd701824fb40c    2.000000
ffd0291168a5aae78274bb933278b960    2.000000
ffd6549fb9066c10c6a644e3b7858f6f    1.500000
ffd7897d9566ab82d72cf51a26757b15    2.666667
fff1c1cf7f7c03de9f8ecf5e562cc3ff    1.625000
Name: Score, Length: 7985, dtype: float64

In [21]:
jcpenney_products['average_product_rating'] = '000bde718ab945188a364aab4d8bcfaa'

In [22]:
# Extracting a record inJcpenny_products where the Uniq_id is 000bde718ab945188a364aab4d8bcfaa
record = jcpenney_products.loc[jcpenney_products['uniq_id'] ==  '000bde718ab945188a364aab4d8bcfaa']

In [23]:
record

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,product_image_urls,brand,total_number_reviews,Reviews,Bought With
6998,000bde718ab945188a364aab4d8bcfaa,pp5006650503,St. John's Bay® Wide Leg Linen Pants,Our pants from St. John's Bay have that classi...,53.18,30.2,,,000bde718ab945188a364aab4d8bcfaa,http://www.jcpenney.com/st-johns-bay-wide-leg-...,http://s7d9.scene7.com/is/image/JCPenney/DP021...,St. John's Bay,8,"[{'User': 'zzku2121', 'Review': 'Discovered th...","[9d9f3cfc76619b167d35fb8e13fea87b, 0abc85a1a28..."
9081,000bde718ab945188a364aab4d8bcfaa,pp5006650503,St. John's Bay® Wide Leg Linen Pants,Our pants from St. John's Bay have that classi...,53.18,30.2,,,000bde718ab945188a364aab4d8bcfaa,http://www.jcpenney.com/st-johns-bay-wide-leg-...,http://s7d9.scene7.com/is/image/JCPenney/DP021...,St. John's Bay,8,"[{'User': 'zzku2121', 'Review': 'Discovered th...","[9d9f3cfc76619b167d35fb8e13fea87b, 0abc85a1a28..."

In [18]:
# Now that jcpenney_products is restored, we can perform the merge
comparison = jcpenney_products.merge(products, left_on='uniq_id', right_on='Uniq_id', how='inner')

In [21]:
comparison

,uniq_id,sku,name_title,description,list_price,sale_price,category,category_tree,average_product_rating,product_url,...,brand,total_number_reviews,Reviews,Bought With,Uniq_id,SKU,Name,Description,Price,Av_Score
0,b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,...,Alfred Dunner,8,"[{'User': 'fsdv4141', 'Review': 'You never hav...","[898e42fe937a33e8ce5e900ca7a4d924, 8c02c262567...",b6c0b6bea69c722939585baeac73c13d,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
1,93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,alfred dunner,jcpenney|women|alfred dunner,3.000,http://www.jcpenney.com/alfred-dunner-essentia...,...,Alfred Dunner,8,"[{'User': 'tpcu2211', 'Review': 'You never hav...","[bc9ab3406dcaa84a123b9da862e6367d, 18eb69e8fc2...",93e5272c51d8cce02597e3ce67b7ad0a,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.000
2,013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,2.625,http://www.jcpenney.com/alfred-dunner-essentia...,...,Alfred Dunner,8,"[{'User': 'pcfg3234', 'Review': 'You never hav...","[3ce70f519a9cfdd85cdbdecd358e5347, b0295c96d2b...",013e320f2f2ec0cf5b3ff5418d688528,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,2.625
3,505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.500,http://www.jcpenney.com/alfred-dunner-essentia...,...,Alfred Dunner,8,"[{'User': 'ngrq4411', 'Review': 'You never hav...","[efcd811edccbeb5e67eaa8ef0d991f7c, 7b2cc00171e...",505e6633d81f2cb7400c0cfa0394c427,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.500
4,d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,You'll return to our Alfred Dunner pull-on cap...,41.09,24.16,view all,jcpenney|women|view all,3.125,http://www.jcpenney.com/alfred-dunner-essentia...,...,Alfred Dunner,8,"[{'User': 'nbmi2334', 'Review': 'You never hav...","[0ca5ad2a218f59eb83eec1e248a0782d, 9869fc8da14...",d969a8542122e1331e304b09f81a83f6,pp5006380337,Alfred Dunner® Essential Pull On Capri Pant,Youll return to our Alfred Dunner pull-on capr...,41.09,3.125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14731,16e3ca6b6a2d3f5da9a81df6cfe7e27a,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,130.67,view all brands,jcpenney|for-the-home|view all brands,3.875,http://www.jcpenney.com/hoover-windtunnel-upri...,...,Hoover,8,"[{'User': 'cced4433', 'Review': '1) the hose i...","[30611c465e893326b8b676ccc5e9e42b, 799d6290601...",16e3ca6b6a2d3f5da9a81df6cfe7e27a,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,3.875
14732,209bec04d9f194616358a77d7b41b314,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,130.67,sale,jcpenney|for-the-home|sale,3.250,http://www.jcpenney.com/hoover-windtunnel-upri...,...,Hoover,8,"[{'User': 'rtbj4421', 'Review': '1) the hose i...","[ac4dcfeca034e705ac2be1a79bbe3acf, c2300c3e551...",209bec04d9f194616358a77d7b41b314,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,3.250
14733,7a8a7cba7b69b4c46ceac1d9666d84f0,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,130.67,vacuums & floorcare,jcpenney|for-the-home|vacuums & floorcare,2.500,http://www.jcpenney.com/hoover-windtunnel-upri...,...,Hoover,8,"[{'User': 'qven4314', 'Review': '1) the hose i...","[fc831da1b1d09b0bd7d6893e9615232f, 9f5f2c625d4...",7a8a7cba7b69b4c46ceac1d9666d84f0,pp5002691549,Hoover® WindTunnel® Upright Vacuum Cleaner,This Hoover® vacuum features dual-stage cyclon...,201.97,2.500
14734,9887bb20c12be3c09d094e97ac8d22be,pp5005921226,Hope Chest Embroidered Quilt & Accessories,,,35.63142,comforters & bedding sets,jcpenney|bed-bath|comforters & bedding sets,3.500,http://www.jcpenney.com/hope-chest-embroidered...,...,Asstd National Brand,8,"[{'User': 'sguz3424', 'Review': 'This product ...","[9968d41d84274b22610278d352f0753a, 7ff057a74f7...",9887bb20c12be3c09d094e97ac8d22be,pp5005921226,Hope Chest Embroidered Quilt & Accessories,NaN,NaN,3.500
14735,2cc49292b44cc12fe22206440d3e7472,pp5005921226,Hope Chest Embroidered Quilt & Accessories,,,35.63142,quilts,jcpenney|bed-bath|quilts,3.000,http://www.jcpenney.com/hope-chest-embroidered...,...,Asstd National Brand,8,"[{'User': 'kcqh1322', 'Review': 'This product ...","[0516719d2624c741610b1815b3d92db9, 81fd62e56b8...",2cc49292b44cc12fe22206440d3e7472,pp5005921226,Hope Chest Embroidered Quilt & Accessories,NaN,NaN,3.000

In [40]:
match_count = comparison['score_match'].value_counts()

In [41]:
match_count

score_match
True     12432
False     2304
Name: count, dtype: int64

In [42]:
# extracting the  Unique_id, average_product_rating, Av_Score columns of the unmathed scores
unmatched_scores = comparison[comparison['score_match'] == False][['uniq_id', 'average_product_rating', 'Av_Score', 'Uniq_id']]

In [46]:
comparison.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14736 entries, 0 to 14735
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   uniq_id                 14736 non-null  object
 1   sku                     14736 non-null  object
 2   name_title              14736 non-null  object
 3   description             14735 non-null  object
 4   list_price              14734 non-null  object
 5   sale_price              14734 non-null  object
 6   category                14734 non-null  object
 7   category_tree           14734 non-null  object
 8   average_product_rating  14734 non-null  float64
 9   product_url             14734 non-null  object
 10  product_image_urls      14734 non-null  object
 11  brand                   14736 non-null  object
 12  total_number_reviews    14736 non-null  int64
 13  Reviews                 14736 non-null  object
 14  Bought With             14736 non-null  object
 15  Uniq_id                 14736 non-null  object
 16  SKU                     14613 non-null  object
 17  Name                    14736 non-null  object
 18  Description             13764 non-null  object
 19  Price                   10734 non-null  float64
 20  Av_Score                14736 non-null  float64
 21  score_match             14736 non-null  bool
dtypes: bool(1), float64(3), int64(1), object(17)
memory usage: 2.4+ MB

In [43]:
unmatched_scores

,uniq_id,average_product_rating,Av_Score,Uniq_id
22,d18479624a12f51d651bb2492243b0c7,3.857143,3.857143,d18479624a12f51d651bb2492243b0c7
23,4f6d3fcd5d7a7da811cca969e074db52,3.285714,3.285714,4f6d3fcd5d7a7da811cca969e074db52
24,40a2c1b7e4da323970d7568fbbbf1797,3.571429,3.571429,40a2c1b7e4da323970d7568fbbbf1797
25,8a6639a5bb4f164f41d4652d6ab8c70d,3.428571,3.428571,8a6639a5bb4f164f41d4652d6ab8c70d
26,9e6a99f8c18f0f17f7ec23931205245f,3.571429,3.571429,9e6a99f8c18f0f17f7ec23931205245f
...,...,...,...,...
14707,2701435b96e0c6a71d3adbecc406162a,1.333333,1.333333,2701435b96e0c6a71d3adbecc406162a
14720,cb3304106ae99247bb3223270f3c56b1,2.666667,2.666667,cb3304106ae99247bb3223270f3c56b1
14721,be2261f852db88995cee4f7bb16cf9d0,3.181818,3.181818,be2261f852db88995cee4f7bb16cf9d0
14726,0101ffcd60d3796f8c26a7ab8ab7f3c6,2.909091,2.909091,0101ffcd60d3796f8c26a7ab8ab7f3c6
14727,cc24e1d5f011291c9cc450e65f11d24f,3.363636,3.363636,cc24e1d5f011291c9cc450e65f11d24f

In [29]:
type(jcpenney_products)

pandas.core.frame.DataFrame

In [44]:
jcpenney_products.astype(str).duplicated().sum()

AttributeError: 'NoneType' object has no attribute 'astype'

In [43]:
# Dropping the duplicate records correctly
# We remove inplace=True when assigning back to the variable to ensure it returns the new DataFrame
jcpenney_products = jcpenney_products.astype(str).drop_duplicates()

In [32]:
# downloading the jcpenny as csv
pd.DataFrame(jcpenney_products).to_csv('jcpenney_products.csv')

In [35]:
products.astype(str).duplicated().sum()

np.int64(0)